"""Regenerate tools/opentrons_api_index.py from a live opentrons install.

Run in a venv with `pip install opentrons==9.0.0`. Output is committed
so the runtime doesn't need opentrons.
"""
from __future__ import annotations
import inspect
import json
import textwrap
from pathlib import Path


def public_methods(cls) -> list[str]:
    out: list[str] = []
    for name, member in inspect.getmembers(cls):
        if name.startswith("_"):
            continue
        if not callable(member):
            continue
        out.append(name)
    return sorted(set(out))


def main() -> None:
    from opentrons.protocol_api import (
        ProtocolContext, InstrumentContext, Labware,
    )
    from opentrons.protocol_api.module_contexts import (
        ThermocyclerContext, MagneticModuleContext, TemperatureModuleContext,
        HeaterShakerContext,
    )

    contexts = {
        "ProtocolContext": ProtocolContext,
        "InstrumentContext": InstrumentContext,
        "ThermocyclerContext": ThermocyclerContext,
        "MagneticModuleContext": MagneticModuleContext,
        "TemperatureModuleContext": TemperatureModuleContext,
        "HeaterShakerContext": HeaterShakerContext,
        "Labware": Labware,
    }
    method_map = {name: public_methods(cls) for name, cls in contexts.items()}

    # Module load names: drawn from validation.ensure_module_model's
    # error message. Hard-coded here because the enum isn't easily
    # introspectable.
    module_load_names = [
        "magdeck", "magnetic module", "magnetic module gen2",
        "tempdeck", "temperature module", "temperature module gen2",
        "thermocycler", "thermocycler module", "thermocycler module gen2",
        "heater shaker", "heaterShakerModuleV1",
    ]

    opentrons_version = __import__("opentrons").__version__
    body = (
        '"""Auto-generated by scripts/regen_opentrons_api_index.py.\n'
        'DO NOT EDIT BY HAND. Regenerate with:\n'
        '    python3 scripts/regen_opentrons_api_index.py\n'
        f'Source: opentrons {opentrons_version}.\n'
        '"""\n'
        'from __future__ import annotations\n'
        '\n'
        f'CONTEXT_METHODS: dict[str, list[str]] = {json.dumps(method_map, indent=4, sort_keys=True)}\n'
        '\n'
        f'VALID_MODULE_LOAD_NAMES: list[str] = {json.dumps(module_load_names, indent=4)}\n'
    )
    Path("tools/opentrons_api_index.py").write_text(body)
    print(f"Wrote tools/opentrons_api_index.py with {sum(len(v) for v in method_map.values())} methods across {len(method_map)} contexts.")


if __name__ == "__main__":
    main()
